---
- name: install dependencies
  zypper: name={{ item }} state=present  
  with_items:
    - xclock
    - xterm*
    - xorg*
    - xauth
    - sapconf
 
- name: craete dir
  file: path=/sapconf state=directory mode=777

- name: copy RPM
  copy: src=files/sapconf-4.1.12-40.47.1.noarch.rpm dest=/sapconf/sapconf-4.1.12-40.47.1.noarch.rpm

#- name: install rpm
#  shell: rpm -U /sapconf/sapconf-4.1.12-40.47.1.noarch.rpm 
#  args:
#    warn: no
#
- name: set PermitRootLogin yes
  lineinfile: dest="{{ sshdconfig }}" insertafter="^UsePAM yes" line="PermitRootLogin yes" state=present
